# Generated by Django 4.1.3 on 2022-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_insumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Últa modificación'),
        ),
    ]
