# Generated by Django 4.1.3 on 2023-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_insumos_l_lista_compras_pedidos_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envases_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('punto_de_pedido', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Últa modificación')),
            ],
            options={
                'verbose_name': 'Envase',
                'verbose_name_plural': 'Envases',
            },
        ),
        migrations.CreateModel(
            name='Insumos_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('unidad', models.CharField(max_length=100)),
                ('punto_de_pedido', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('lote', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Últa modificación')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Productos_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('punto_de_pedido', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('lote', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.RenameModel(
            old_name='Lista_compras',
            new_name='Lista_compras_li',
        ),
        migrations.RenameModel(
            old_name='Pedidos_productos',
            new_name='Pedidos_productos_li',
        ),
        migrations.DeleteModel(
            name='Envases',
        ),
        migrations.DeleteModel(
            name='Insumos_l',
        ),
        migrations.DeleteModel(
            name='Productos_l',
        ),
    ]
