# Generated by Django 4.1.3 on 2023-01-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_pedidos_productos_l_delete_pedidos_productos_li'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tel', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.RenameModel(
            old_name='Pedidos_productos_l',
            new_name='Pedidos_productos_li',
        ),
        migrations.RenameField(
            model_name='pedidos_productos_li',
            old_name='nombre',
            new_name='productos',
        ),
    ]
