# Generated by Django 4.1.3 on 2023-01-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_pedidos_productos_l_delete_pedidos_productos_li'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_intermedio_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('id_pedido', models.IntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Últa modificación')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
