# Generated by Django 4.1.3 on 2023-01-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_pedido_intermedio_li'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido_intermedio_li',
            options={},
        ),
        migrations.AlterField(
            model_name='pedido_intermedio_li',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.pedidos_productos_l'),
        ),
    ]
