# Generated by Django 4.1.3 on 2023-01-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_alter_pedido_intermedio_li_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_productos_l',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidos_productos_l',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidos_productos_l',
            name='productos',
        ),
    ]
