# Generated by Django 4.1.3 on 2023-01-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0014_pedidos_productos_li_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_productos_li',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidos_productos_li',
            name='productos',
        ),
        migrations.AlterField(
            model_name='pedidos_productos_li',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
