# Generated by Django 4.1.3 on 2023-01-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_remove_pedidos_productos_li_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_productos_li',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
