# Generated by Django 4.1.3 on 2023-01-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0017_alter_pedido_intermedio_li_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido_intermedio_li',
            new_name='Pedido_intermedio_l',
        ),
    ]
