# Generated by Django 4.1.3 on 2023-01-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0018_rename_pedido_intermedio_li_pedido_intermedio_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_intermedio_li',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Últa modificación')),
                ('cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocke', to='gestor.productos_li')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.pedidos_productos_li')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.productos_li')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido_intermedio_l',
        ),
    ]
