# Generated by Django 4.1.3 on 2023-01-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0019_pedido_intermedio_li_delete_pedido_intermedio_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_intermedio_li',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
