# Generated by Django 4.1.3 on 2023-01-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0020_alter_pedido_intermedio_li_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos_productos_l',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('entregado', models.BooleanField(default='False')),
                ('pagado', models.BooleanField(default='False')),
                ('estado', models.CharField(default='Pendiente', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.clientes_li')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AlterField(
            model_name='pedido_intermedio_li',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.pedidos_productos_l'),
        ),
        migrations.DeleteModel(
            name='Pedidos_productos_li',
        ),
    ]
