# Generated by Django 4.1.3 on 2023-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0022_pedidos_productos_li_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_productos_li',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
    ]
